### ISSUE TITLE
Fix bugs: Align Navbar spacing to sync with UI/UX design

### ISSUE THREAD

**Issue by geekelo** [geekelo/travelsi-user-frontend-app#5]
![image](https://github.com/geekelo/travelsi-user-frontend-app/assets/102464578/f63fccad-4e21-49b7-87b3-8bb20bac554f)

![Screenshot from 2024-05-25 10-21-36](https://github.com/geekelo/travelsi-user-frontend-app/assets/102464578/a7aaeefc-1926-4cbf-93fc-8cca4484e6c3)

- [ ] I noticed the space around the navbar is smaller than the one in the template. Increasing the space is important because the text in the header section is expected to align with the space around the navbar also
- [ ] Again the space between the profile picture and the search button is equal with the space between the navlinks. This doesn't create emphasis around it as it is not a navlink and shouldn't appear as one. You can revert to the template to see how.
- [ ] Did you make provisions for light and dark theme changes?

Aside these changes, I can say you have done a great job within a short time. Kudos @Chandan-devs-tech

**Comment by Chandan-devs-tech** [comment]
![Screenshot 2024-05-27 180243](https://github.com/geekelo/travelsi-user-frontend-app/assets/65088027/8cf944b1-c2ef-4aad-bc26-f917b623b5b2)

## I have implemented the changes you suggested:

- [x] Increased Navbar Space: I have adjusted the spacing around the navbar to ensure that the text in the header section aligns properly with the navbar, matching the template more closely.
- [x] Profile Picture and Search Button Spacing: The space between the profile picture and the search button has been increased to distinguish it from the navlinks, creating a clearer emphasis.

### Please review the changes and let me know @geekelo if there are any further adjustments needed.

**Comment by geekelo** [comment]
#4
