### ISSUE TITLE
Fix Bugs: Sticky Navbar 

### ISSUE THREAD

**Issue by geekelo** [geekelo/travelsi-user-frontend-app#8]
- [x] Sticky Nav should stick to the top of the page on scrolling both for desktop and mobile screens
- [x] Reduce the space between the edge of the page and the mobile menu icon. The menu icon seems pushed in a bit. 
Thanks

**Comment by Chandan-devs-tech** [comment]
### Hi @geekelo ,

### The issue with the sticky navbar has been resolved. The navbar now properly sticks to the top of the page when scrolling on both desktop and mobile screens. Additionally, the space between the edge of the page and the mobile menu icon has been reduced, ensuring the icon is no longer pushed in.

### Thank you for reporting these issues. Please review the changes and let me know if there are any further adjustments needed.

### _Here is how it looks after the updates:_

<img src="https://github.com/geekelo/travelsi-user-frontend-app/assets/65088027/e652a13d-40ea-4027-8722-623ed1e26116" alt="Updated view - Desktop Version" width="800"/>

<img src="https://github.com/geekelo/travelsi-user-frontend-app/assets/65088027/07953855-725d-4361-9ef9-40a677c9a83d" alt="Updated view - Desktop Version 01" width="800"/>

<img src="https://github.com/geekelo/travelsi-user-frontend-app/assets/65088027/2d67bdce-0828-494b-93a5-9470cda31ba8" alt="Updated view - Mobile Version" width="400"/>

<img src="https://github.com/geekelo/travelsi-user-frontend-app/assets/65088027/9701f454-243f-4f98-831c-0581c975fd3b" alt="Updated view - Mobile Version 01" width="400"/>
